language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip --version
  - pip install coverage
  - pip install requests
  - pip install SQLAlchemy
  - pip install flask
  - pip install flask-SQLAlchemy
  - pip install pyelasticsearch
  - pip install MySQL-python

# execute any number of scripts before the test run.
before_script:
  - uname -a
  - printenv
  - pip list

# command to run tests
script:
  - date
  - ls -al
  - ls -al
  - ls -al
